apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-hello
  namespace: default
  labels:
    app: spark-hello
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "sparkpi"
  # https://skaffold.dev/docs/environment/local-cluster/
  #  Skaffold’s direct loading of images into a local cluster does mean that resources specifying an
  # imagePullPolicy: Always may fail as the images are not be pushed to the remote registry.
  # On Docker for Desktop, don't specify imagePullPolicy
  # imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark/work-dir/runpi.py
  sparkConf:
    "spark.ui.port": "4040"
  sparkVersion: "3.2"
  restartPolicy:
    type: Never
  driver:
    coreLimit: "3"
    coreRequest: "1"
    memory: "1g"
    labels:
      version: "3.2"
    serviceAccount: spark
  executor:
    coreLimit: "3"
    coreRequest: "1"
    instances: 1
    memory: "1g"
    labels:
      version: "3.2"
  dynamicAllocation:
    enabled: true
    initialExecutors: 1
    minExecutors: 1
    maxExecutors: 8
